# -*- coding: utf-8 -*-
"""TrainingSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rizS0UxU90YSMwuZsXC-Hj5hcb0xeo4l
"""

# import all required libraries
import pandas as pd
import os
import matplotlib.pyplot as plt
import re

print("Libraries imported successfully.")

# Defining functions

def extract_merchant_signals(cleaned_text, merchant_keywords):
    """Identifies the presence of specified merchant keywords in a cleaned text string.

    Args:
        cleaned_text (str): The cleaned text string to analyze.
        merchant_keywords (list): A list of merchant keywords to look for.

    Returns:
        dict: A dictionary of boolean flags (e.g., {'has_rent': True, 'has_tesco': False})
              indicating the presence of each keyword.
    """
    signals = {}
    for keyword in merchant_keywords:
        signals[f'has_{keyword}'] = keyword in cleaned_text
    return signals

def transaction_type(df):
    """Returns data with the columns detailing on the transaction type."""
    merchant_keywords = ['rent', 'tesco', 'restaurant', 'salary', 'utility', 'transport']
    df = df[['transaction_id','customer_id','description']]
    # loop to apply the function for each row and then concatenate the results
    signals_df = df['description'].apply(lambda x: pd.Series(extract_merchant_signals(x, merchant_keywords)))
    df = pd.concat([df, signals_df], axis=1)
    merchant_signal_columns = [col for col in df.columns if col.startswith('has_')]
    merchant_signals_df = df[['customer_id'] + merchant_signal_columns].groupby('customer_id').any().reset_index()
    return merchant_signals_df


def merge_dataframes(transactions_df, labels_df):
    """Merges the transactions and labels DataFrames on 'customer_id'."""
    merged_df = pd.merge(labels_df,transactions_df, on='customer_id', how='left')
    return merged_df

def analyze_transactions(df):
    """Calculates total debit, total credit, and average transaction amount ."""
    customer_features_df = df.groupby('customer_id').agg(
    num_transactions=('transaction_id', 'count'),
    total_debit=('amount', lambda x: x[df.loc[x.index, 'txn_type'] == 'debit'].sum()),
    total_credit=('amount', lambda x: x[df.loc[x.index, 'txn_type'] == 'credit'].sum()),
    average_transaction_amount=('amount', 'mean')
    ).fillna(0)
    return customer_features_df

def clean_text(text):
    """Converts text to lowercase and removes punctuation and numbers."""
    text = text.lower()
    text = re.sub(r'[\W_]+', ' ', text) # Remove punctuation and replace with space
    text = re.sub(r'\d+', '', text) # Remove numbers
    return text

print("Functions defined successfully.")

#Main Code

#load the data into dataframes
transactions_df = pd.read_csv('/content/sample_data/transactions.csv')
labels_df = pd.read_csv('/content/sample_data/labels.csv')
print("Raw data has been loaded into dataframes.")

transactions_df['description'] = transactions_df['description'].apply(clean_text)
print("Description field has been cleaned.")

# Merging source file
merged_transactions_df = merge_dataframes(transactions_df, labels_df)

# Call function which calculates additional features
customer_features_df = analyze_transactions(merged_transactions_df)
transaction_type_df = transaction_type(merged_transactions_df)

# Merge all datasets to form a training-ready dataset
training_df = pd.merge(labels_df,customer_features_df, on='customer_id', how='left')
training_df = pd.merge(training_df,transaction_type_df, on='customer_id', how='left')
print("Training DataFrame with aggregated features and labels has been created")
display(training_df.head())

# Create the 'artifacts' directory if it doesn't exist
os.makedirs('artifacts', exist_ok=True)
# Save the training_df to a CSV file
training_df.to_csv('artifacts/training_set.csv', index=False)
print("training_df saved to artifacts/training_set.csv")

#Exploratory Data Analysis 1 -Defaulted customers
# Generate count plot for the target variable 'defaulted_within_90d' -
plt.figure(figsize=(6, 4))
sns.countplot(x='defaulted_within_90d', data=training_df)
plt.title('Distribution of Defaulted Within 90 Days')
plt.xlabel('Defaulted Within 90 Days')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['No Default (0)', 'Default (1)'])
plt.show()
plt.close() # Close the figure to free memory and prevent display if not desi

#Exploratory Data Analysis 2 -Spending Categorization
#Plotting the number of customer under each spending category

has_columns = [col for col in training_df.columns if col.startswith('has_')]
has_counts = training_df[has_columns].sum()

plt.figure(figsize=(10, 6))
sns.barplot(x=has_counts.index, y=has_counts.values, hue=has_counts.index, palette='viridis', legend=False)
plt.title('Customer Counts for Each \'has_\' Category')
plt.xlabel('Category')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()
plt.close() # Close the figure to free memory and prevent display if not desired